import type { Metadata } from 'next'
import './globals.css'
import HOCProvider from '../global-components/hocs/HOCProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <HOCProvider>
        <body>{children}</body>
      </HOCProvider>
    </html>
  )
}
